version: '3.9'  # Обновленная версия

services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: autoservice
      MYSQL_USER: autoservice_user
      MYSQL_PASSWORD: autoservice_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: autoservice-backend-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: autoservice-backend
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: autoservice_user
      DB_PASSWORD: autoservice_password
      DB_NAME: autoservice

volumes:
  db_data:
